version: '3.3'

services:
  jenkins:
    image: amitbarai/myjenkins
    container_name: myjenkins
    deploy:
      replicas: 1
      resources:
        limits: 
          memory: 400m
        reservations:
          memory: 200m
      restart_policy:
        condition: on-failure    
    user: root
    environment:
      - JENKINS_SLAVE_AGENT_PORT=50001
    container_name: myjenkins
    ports:
      - "80:8080"
    volumes:
      - /app/docker/jenkins/data:/var/jenkins_home
    networks:
      - Jenkinsnet
  tomcat-dev:
    image: amitbarai/mytomcat
    container_name: tomcat-dev
    volumes:
      - vol-dev
    networks:
      - Jenkinsnet
    ports:
     - "8081:8080"
  tomcat-prod:
    image: amitbarai/mytomcat
    container_name: tomcat-prod
    volumes:
      - vol-prod
    networks:
      - Jenkinsnet
    ports:
      - "8082:8080"
networks:
  Jenkinsnet:
    driver: overlay

volumes:
  vol-dev:
  vol-prod:


